### ISSUE TITLE
How to init OpenGL in Linux?

### ISSUE THREAD

**Issue by tianhanghai** [GPUOpen-LibrariesAndSDKs/AMF#176] opened 2019-08-21 10:04 UTC
I am wondering how to use  
`virtual AMF_RESULT          AMF_STD_CALL InitOpenGL(amf_handle hOpenGLContext, amf_handle hWindow, amf_handle hDC) = 0;`
I don't know how to fill the parameters in Linux.   
I use glfw to Create OpenGL window. In `glfw3native.h`,it provides interfaces as following.
```
#if defined(GLFW_EXPOSE_NATIVE_GLX)
/*! @brief Returns the `GLXContext` of the specified window.
 *
 *  @return The `GLXContext` of the specified window, or `NULL` if an
 *  [error](@ref error_handling) occurred.
 *
 *  @thread_safety This function may be called from any thread.  Access is not
 *  synchronized.
 *
 *  @since Added in version 3.0.
 *
 *  @ingroup native
 */
GLFWAPI GLXContext glfwGetGLXContext(GLFWwindow* window);

/*! @brief Returns the `GLXWindow` of the specified window.
 *
 *  @return The `GLXWindow` of the specified window, or `None` if an
 *  [error](@ref error_handling) occurred.
 *
 *  @thread_safety This function may be called from any thread.  Access is not
 *  synchronized.
 *
 *  @since Added in version 3.2.
 *
 *  @ingroup native
 */
GLFWAPI GLXWindow glfwGetGLXWindow(GLFWwindow* window);
```
Can you show me how to init encoder with existed opengl context in Linux?

**Comment by MikhailAMD** [comment] 2019-08-22 22:43
On Linux AMF encoder works via Vulkan only. Check DeviceVulkan.cpp for Vulkan device creation. OpenGL can be initialized like this: context->InitOpenGL(GLXContext hOpenGLContext, Window xWindow or NULL, NULL);

**Comment by tianhanghai** [comment] 2019-08-23 02:34
Here is my code.
```
t_res = amf::AMFContext1Ptr(m_p_context)->InitVulkan(NULL);
	if(t_res != AMF_OK && t_res != AMF_ALREADY_INITIALIZED){
		t_stat = MW_VENC_STATUS_FAIL;	// init vulkan failed
		m_b_create_encoder = false;
		return t_stat;
	}
	
	if (m_mem_type_in == amf::AMF_MEMORY_OPENGL) {
		printf("init opengl %p %p %p\n",p_opengl_param->m_p_opengl_context,
			p_opengl_param->m_p_window,
			p_opengl_param->m_p_dc);
		t_res = m_p_context->InitOpenGL(
			p_opengl_param->m_p_opengl_context,
			p_opengl_param->m_p_window,
			p_opengl_param->m_p_dc);
		if (t_res != AMF_OK&&t_res != AMF_ALREADY_INITIALIZED) {
			t_stat = MW_VENC_STATUS_FAIL;
			m_b_create_encoder = false;
			printf("init opengl failed\n");
			return t_stat;
		}
		else{
			printf("init opengl succeeded\n");
		}
	}
```
vulkan alsways succeed while InitOpenGL always leads to `Segmentation fault (core dumped)`,
I try to fill all filters will NULL, it still leads to `Segmentation fault (core dumped)`.  
Is there something wrong with my environmemt or something else ?

**Comment by MikhailAMD** [comment] 2019-08-23 14:43
It looks like the problem is on our side. I will ask a developer to reproduce and fix if needed.

**Comment by tianhanghai** [comment] 2019-09-04 08:51
Is there anything new ?

**Comment by MikhailAMD** [comment] 2019-09-04 13:36
This is work in progress. We didn't forget. Thanks for your patience.

**Comment by MikhailAMD** [comment] 2020-02-05 22:18
This should be fixed in public driver.

**Closed** 2020-12-20 23:18 UTC
