### ISSUE TITLE
[Bug]: Detecting Handle leaks for AMF (after call InitDX11)

### ISSUE THREAD

**Issue by VitaliiGitHub** [GPUOpen-LibrariesAndSDKs/AMF#506] opened 2024-09-24 09:48 UTC
I think I found a handle leak in AMF. The project CPPSamples\SimpleDecoder was used as a base to demonstrate the issue. If the InitDX11 method is called, after the resources are released, one handle of type 'Thread' remains open. There is no such problem with InitDX9 and InitDX12 or InitVulkan calls.

 - OS: Windows 10/11
 - Driver Version 24.8.1
 - GPU RX 5700 XT

 Code:
![amf](https://github.com/user-attachments/assets/8f4c98bf-5162-49f4-95a5-51ba4e0c9c48)

**Comment by MikhailAMD** [comment] 2024-09-24 21:10
AMF doesn't create internal threads, except few special cases as PA. My guess is that it is dx11 driver, which is by definition submits all jobs from a secondary thread. You can see who created the thread by breaking into debugger after termination.
Or create dx11 device outside of AMF and pass it to InitDX11.
If it is DX11 issue, it could be intended or unintended.

**Comment by VitaliiGitHub** [comment] 2024-09-25 09:05
![dx](https://github.com/user-attachments/assets/ef24b7cd-b393-4a8c-b5b9-3afa1b53a21a)

Yes, you are right, the D3D11CreateDevice call spawns threads and releases them when the device is destroyed, but handles of type Thread remain open. This happens even without AMF. This is an issue with the AMD driver. Could you advise where to report this problem further?

**Comment by MikhailAMD** [comment] 2024-09-25 12:25
It is not necessary a bug. If it is a one thread and not a leak that adds thread every time app creates and destroys device object, it is not a big deal.
You can add a loop to verify this, I will ask driver owners.

**Comment by VitaliiGitHub** [comment] 2024-09-25 15:21
For demonstration purposes, I created a loop where I create and destroy a DX11 device (see above), and handles are leaking. The exact same code on NVIDIA works without leaks. Here, for example, is a loop with 5,000+ iterations and what the graph looks like:

![t1](https://github.com/user-attachments/assets/fcfe0ff6-bdfa-4834-8732-cd98126c768c)

Results from Handle viewer:

![t2](https://github.com/user-attachments/assets/3fb6092e-97d8-46ff-bc37-9af39939d851)

Background: The issue was discovered during the decoding of a large number of files, where the AMF decoder was recreated with InitDX11(with a new DX device) for each file, and metrics showed me a handle leak. Initially, I thought the issue was with AMF, but it turned out that the problem is with the creation of the DX device on AMD.

**Comment by MikhailAMD** [comment] 2024-09-27 13:32
Thanks for the detailed info. D3D11 driver team confirmed the problem and made a fix. Not yet sure when public driver gets it.

**Comment by abdylaV** [comment] 2024-09-27 17:20
Thank you so much for your help! Then I think we can close this issue here.

**Comment by VitaliiGitHub** [comment] 2024-09-27 17:22
Thank you so much for your help! Then I think we can close this issue here.

**Comment by VitaliiGitHub** [comment] 2024-09-27 17:23
Thank you so much for your help! Then I think we can close this issue here.

**Closed** 2024-09-27 17:22 UTC
Labels: bug
