### ISSUE TITLE
Undocumented backward incompatible changes in v1.4.23

### ISSUE THREAD

**Issue by e00E** [GPUOpen-LibrariesAndSDKs/AMF#287] opened 2021-12-16 21:20 UTC
I have existing code that was compiled with amf 1.14.21 and ran correctly with driver 21.10.2. With the new driver 21.12.1 that ships with amf 1.4.23 it no longer works.

AVC and HEVC: With rate control method CQP, setting target bitrate errors. I understand that target bitrate might have no meaning for CQP but nonetheless this was previously accepted and the documentation does not forbid this combination.

HEVC: Setting NUM_GOPS_PER_IDR to 0 fails. This was previously accepted and the pdf documentation explicitly allows 0 in the description text.

**Comment by e00E** [comment] 2021-12-16 21:24
The errors occur regardless of whether I initialize amf with the older compile time version (from Version.h) or the runtime version from (from AMFQueryVersionFn).
I have not yet updated my AMF headers so I do not know if doing this would fix the problem.

**Comment by rhutsAMD** [comment] 2022-01-07 23:35
Yes, there is no meaning for setting the target bitrate for RATE_CONTROL_METHOD_CONSTANT_QP since the bitrate will vary based on the scene’s complexity, not the target bitrate which is set. We have removed the limitation for setting the target bitrate with rate control method CQP so that this older behaviour will be restored and will be available in a future driver update.

I have updated acceptable range for the `AMF_VIDEO_ENCODER_HEVC_NUM_GOPS_PER_IDR` property to allow values of 0, as mentioned in the documentation. This will be available in a future driver update as well. Thank you for helping us catch these regressions. We will notify you once the driver with the fix is made publicly available.

Regarding the version you are initializing with, it is important to pass the version from the headers you are using.

**Comment by jamesstringerparsec** [comment] 2022-01-24 19:14
@rhutsAMD we're also having bad behaviour with `PREENCODE_ENABLE` with HEVC also.  Can you please check this out?

**Comment by rhutsAMD** [comment] 2022-01-27 21:05
I am not able to reproduce the crashing issue with `AMF_VIDEO_ENCODER_HEVC_PREENCODE_ENABLE` on the latest public driver 22.1.2, while I can still reproduce the original other errors in this issue since the fix has not yet landed in publicly available drivers.

Could you please provide some further information such as your machine’s configuration, including driver version, as well as some logs during the crash, crash dump, and the properties you are setting before encoder initialization?

**Comment by rhutsAMD** [comment] 2022-03-25 15:47
The fixes for the original issues of setting target bitrate after setting rate control method CQP and setting NUM_GOPS_PER_IDR to 0 are confirmed to be working in the latest public Adrenalin 22.3.1 recommended driver.

**Closed** 2022-04-06 14:03 UTC
