### ISSUE TITLE
Wrong colors decoded

### ISSUE THREAD

**Issue by Peter-N-HB** [GPUOpen-LibrariesAndSDKs/AMF#213] opened 2020-05-04 13:16 UTC
Hi Mikhail

We are using the the AMF SDK in an NLE plugin to decode HEVC. On some footage the colors on the images the decoder outputs are messed up.
It can also be reproduced by means of the PlaybackHW sample app.

On this 10 bit source clip the red channel seems to be completely missing:
https://www.dropbox.com/s/cyj36pgzr2stp54/HEVC_Main10L5.1_420_10bit.MOV?dl=1

On the 8 bit clip below we can see areas in the image shifting colors
https://www.dropbox.com/s/jpoo207phepiqga/Sony_Mexico_4K_Demo__MainL5.1_420_8bit_QFHD_5994fps_BT709.mp4?dl=1

See also this screenshot taken from PlaybackHW:
https://www.dropbox.com/s/r1wfynnsdbpx1h9/AMF_dec_bad_colors.PNG?dl=0

We also see that PlaybackHW displays some clips too bright, but that may be a different thing, as we do not get that in our implmentation.

GPUs we are using for the tests are RTX 560 and RTX 580. Drivers are the most recent v20.4.2

Do you reproduce the color shifts?

Thanks,
Peter

**Comment by MikhailAMD** [comment] 2020-05-06 13:32
Thanks for bringing this up. I've found two issues and opened an internal ticket.

**Comment by MikhailAMD** [comment] 2020-06-02 20:37
The decoder fix is in pipeline for release in a hotfix driver. I will post here when It is released.

I have a problem with color conversion of HEVC_Main10L5.1_420_10bit.MOV file you shared. This is 10 bit HEVC stream. In VUI header, the  transfer function is set to 709 (ITU-R BT.709-5) -  "transfer_characteristics" in HEVC spec.  But when I try to apply 709 to linear algorithm it is too bright. When I try to apply PQ algorithm (SMPTE ST 2084) it looks good but I really don't want to put such hack in the driver. 
Also If you check D3D11 video processor, it doesn't have 709 transfer curve in whole enumeration (check ID3D11VideoContext1::VideoProcessorSetOutputColorSpace1() - DXGI_COLOR_SPACE_TYPE).
So it looks like exotic combination. How did you get this file? I don't have any other HEVC HDR files with 709 transfer function.

**Comment by Peter-N-HB** [comment] 2020-06-03 08:39
Thanks for your efforts. Looking forward to the new driver.

Regarding the the 10 bit file with Color Primaries and Martix coefficients set to BT.2020 but Transfer Characteristic set to BT.709, I think it is a rare but maybe possible combination. This file is from a big camera manufacturer, but perhaps an early prototype. Actually, on (AVC) samples from an other manufacturer Transfer Characteristic is set to 14, BT.2020 in this combination.
However, in the HEVC specification table E.4 for value 14 it says "functionally the same as the values 1, 6, and 15" where 1 is BT.709. So maybe it is legal to set BT.709 in this combination. But I will talk to the manufacturer and ask whether this was intended. I keep you updated.

But for our use case we need the raw output of the decoder w.o. any color transformations applied. Those are applied by the host NLE and the plugin only communicates the three color information values to the host.

**Comment by MikhailAMD** [comment] 2020-06-03 13:44
The value is legal. But the problem is that it looks good only when I force value to 16  (2084 or PQ). 
I will keep you posted on the driver release.

**Comment by MikhailAMD** [comment] 2020-07-09 22:31
The decode issue has been fixed for both clips in 20.7.1 driver release (July 9, 2020). Color conversion fix will follow. Never mind my comments about transfer characteristic, figured this out, the clip is valid.

**Comment by Peter-N-HB** [comment] 2020-07-15 11:30
Hi Mikhail,

Thanks,
I can confirm that decoding now works properly on all the affected footage in our use case here with the new drivers installed.

**Closed** 2020-12-20 23:24 UTC
