### ISSUE TITLE
SimpleEncoder Colors Issues

### ISSUE THREAD

**Issue by TheElixZammuto** [GPUOpen-LibrariesAndSDKs/AMF#261] opened 2021-04-30 10:15 UTC
Hi everyone,
I modified the SimpleEncoder example to draw three squares with these NV12 Colors:

    FillNV12SurfaceWithColor(pColor4, 0, 128, 128);
    FillNV12SurfaceWithColor(pColor3, 15, 128, 128);
    FillNV12SurfaceWithColor(pColor2, 31, 128, 128); 
    FillNV12SurfaceWithColor(pColor1, 64, 128, 128);

This should give 3 squares with different colors, but two of these 3 have the same color on screen.

I tried to set `AMF_VIDEO_ENCODER_FULL_RANGE_COLOR` to `true`,
and both `AMF_VIDEO_ENCODER_INPUT_COLOR_PROFILE` and `AMF_VIDEO_ENCODER_OUTPUT_COLOR_PROFILE` to `AMF_VIDEO_CONVERTER_COLOR_PROFILE_FULL_709`, and while the problem is still present, Full Range Color is detected by MPC

I attached the output of the program for Partial and Full Color Range Below
[simpleencoder_outputs.zip](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/6404580/simpleencoder_outputs.zip)

My Graphics Card is a Radeon Vega 11 on Ryzen 2400G
The driver version is 27.20.15003.5017
Windows 10 version is 20H2

Thank you in advance for the support

**Comment by MikhailAMD** [comment] 2021-04-30 15:11
Could you please share full code for modified sample?

**Comment by TheElixZammuto** [comment] 2021-04-30 18:04
Hi,
The modifications are available on this GitHub gist

https://gist.github.com/TheElixZammuto/67b763c767a8eea1b9ecbcd553eac1a4

Il ven 30 apr 2021, 17:12 Mikhail_AMD ***@***.***> ha scritto:

**Comment by MikhailAMD** [comment] 2021-04-30 20:02
Thanks for source. I assume you are using PlaybackHW sample to check the stream. The stream is good but the problem is AMF CSC handling full range.  Once fixed, the player shows proper colors. I will push the fix to driver.

**Comment by TheElixZammuto** [comment] 2021-04-30 20:25
Tried it with PlaybackHW and Media Player Classic, both with the same issue. By the way, thank you for the very fast response, hoping to test this very soon!

**Comment by MikhailAMD** [comment] 2021-06-23 22:03
This should be fixed with the latest driver release (21.6.1)

**Comment by rhutsAMD** [comment] 2023-10-26 21:30
Closing as fixed starting in driver release 21.6.1.

**Closed by rhutsAMD** 2023-10-26 21:30 UTC
Labels: fixed / done
