### ISSUE TITLE
2 questions about needed DLLs in AMD Driver for AMF

### ISSUE THREAD

**Issue by Benman2785** [GPUOpen-LibrariesAndSDKs/AMF#109] opened 2017-10-27 18:53 UTC
Hi,
which DLLs do i need to have AMF 1.4.6.0 working in any driver version that already had AMF - or specific: Driver 17.6.2

i use amdh264enc64.dll; amdh265enc64.dll; amdmcl64.dll; amd_opencl64.dll; amfrt64.dll; - and most of it worked -> but no H265 - so i think i am missing something

its widely about what is broken: AMF or AMD Crimson since 17.7.2
regarding: https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/283 && https://github.com/Xaymar/obs-studio_amf-encoder-plugin/issues/263

would be nice if you can help me with that ;)

**Comment by MikhailAMD** [comment] 2017-10-27 19:03
I am not sure why do you want to jungle with DLLs. You may want to just reinstall the latest driver.

**Comment by Benman2785** [comment] 2017-10-27 19:33
it is to test if the bug is in AMF or in the part of the driver they changed in 17.7.2 (the first driver with reduced latency)

**Comment by Benman2785** [comment] 2017-10-27 19:34
https://community.amd.com/thread/221627

**Comment by MikhailAMD** [comment] 2017-10-27 19:57
the MFT DLLs that are outside of System32 folder are irrelevant. There is no guarantee that replacing amf and / or opencl DLLs will work. Nobody testing this. 17.7.2 driver is from July. So can you reproduce the problem with the latest driver?

**Comment by Benman2785** [comment] 2017-10-27 20:06
yes in 17.10.2 the error still persists - even with a new GPU

**Comment by MikhailAMD** [comment] 2017-10-27 20:27
If you have a system crash then it is not amf or opencl or any user mode component. I will ask someone to reproduce and log a bug.

**Comment by Benman2785** [comment] 2017-10-28 09:32
i have the logs in the AMD Community Support Forum or in the other 2 links i provided ;)

and usually its only the Driver and/or the Game that crashes

have in mind i have 2 Screens - that can be also a part of the Problem

**Comment by Benman2785** [comment] 2017-10-28 09:34
oh and replacing the DLLs worked ;) - but as i said i dont know if i copied all needed dlls into system32
and with worked i mean: OBS reported i use AMF 1.4.6.0 in driver 17.6.2 - and it recorded/streamed in h264 with prepass ;)

**Comment by Roph** [comment] 2017-10-31 20:55
I'll just add, we have the exact same Sapphire Nitro+ OC 4GB RX 580 GPU, and mine was unstable at its "stock" 1411Mhz. 

Running more demanding games in conjunction with streaming would result in crashes. All I did was flick the physical BIOS switch on the GPU so it uses the other "quiet" BIOS and runs at 1340Mhz instead, and it's been rock solid stable since.

So maybe try using the other BIOS? rule out hardware instability :)

**Comment by Benman2785** [comment] 2017-10-31 20:58
@Roph same happened with RX480 8G - even when i underclocked

and other have confirmed it that it is a driver problem of 17.7.2 and later with HWacc, DirectDraw and Direct3D

btw - when i use driver 17.6.2 with AMF from 17.10.3 it works fine - thats why its not the plugin nor amf

**Comment by Benman2785** [comment] 2017-10-31 20:59
btw pls post this https://community.amd.com/thread/221627 there ;)

**Comment by MikhailAMD** [comment] 2017-10-31 21:06
Hold on, you lost me, Questions:
1. Does the crash happen with **unmodified** (frequency, bios etc. card)?
2. Does it happen with the latest **unmodified** driver for this **unmodified** card?

**Comment by Benman2785** [comment] 2017-10-31 21:34
crash did happen with unmodified Card on RX480 8G & RX580 4G (both Nitro+ OC) since 17.7.2 (latest stable 17.6.2)

crash did happen on slightly underclocked GPUs; crash rarely happens when clocked as reference

**Comment by SPIKEYPUP** [comment] 2017-11-01 09:45
I can concur with Benman2785 regarding the issues.  I am sorry I cannot post more detail right now, but will give you a full rundown of where I have been experiencing issues since 17.7+, 17.6.2 was also the LAST STABLE for me, however, since Fall Creator's Update, it no longer works for me in a stable fashion, regardless of clocks/default states, etc.  Promise I will post more details as I know this blurb doesn't help much but I wanted you to know at least that this hasn't been an isolated case, and has been causing me trouble since 17.7+, and especially more so now with Fall Creators update, 17.4.4-17.6.2 is no longer stable for me for video encoding/decoding either.  I've also tried from multiple fresh O/S installations each time using all the drivers from 17.6.2 up to 17.10.3 and the problem persists fully.  Particularly any video rendering work will start to lag massively, then encdoer lags, all synch is lost  (specifically when doing something like Game Capture or even without capturing, just while engaging 3D) and nothing can recover usually ends up in driver crash or massive frame skipping.  If I am NOT in the active 3D game/app, things are OK (not good but OK, still has encode and render lag but very light) but the moment the 3D app is in focus, everything falls apart.  I will again send more details as well as video capture examples and capture of what is happening as it happens so you can see what I mean.  In particular I was using Newtek NDI a lot for my workflow, now I cannot really use it at all in the active flow, even without it, encode/decode is very problematic if not impossible, then when 3D is thrown into the mix, Encode is completely unusable.  Relive recording tools (above mentioned was about OBS) seem OK for the most part but performance seems definitely affected especially since Fall Creators Update.  Again sorry for lack of details, please give me a day or two to prepare things, I am very busy at the moment, and I just wanted to get this info out asap while I prepare the data.  Thanks for understanding!  I'll be back with more soon...

**Comment by SPIKEYPUP** [comment] 2017-11-01 16:40
OK... New Finding... Explicitly shutting down Game Mode (I allowed game bar to be active, and turned off game mode by bringing up the bar in the 3D app that was problematic) in FCU (Fall Creators Update) normalized my NDI Output and reduced Avg time to render when 3D application active by almost 50%, from 4-5.5ms/frame to 2-2.5ms/Frame, spikes from 6-9ms gone, testing to confirm.  Concurrently streaming at 15Mbps output on H264 no longer causing stalls or skipped frames, or missed render lag frames... This is very encouraging for me, I do not understand how I missed this.  This implies that Game Mode is enabled by default even when not allowing Game Bar Etc. and Game Bar MUST be activated to TURN OFF Game Mode.  This is obviously a Windows issue that MS MUST address.  This was not the previous default activity prior to 1709 as far as I'm aware...Game Bar had to be enabled in order to toggle Game Mode.  This also indicates that Game Mode is not working well with the current implementation somewhere in the graphics subsystem or stack.  As it is completely crippling to the rendering of 3D, and encode/decode of video when performing those tasks simultaneously.  Currently I am testing using 17.6.2 as of this moment.  Just an update...

**Comment by SPIKEYPUP** [comment] 2017-11-03 19:53
OK I'm still working on this, but I'd say I have success in the root cause of failure when using 17.6.2, it IS windows Game mode.  You must explicitly use game bar to explicitly disable it, even if game bar is disabled, it does not disable game mode, as was previous behavior.  Something is definitely wrong yet right when you think about it, Windows is trying to ensure the best performance for the app, but when trying to copy buffers etc. it seriously handicaps the ability of other hooks etc.  I just finished an 8.5 hour stream, 41.2GB of data transfer, 12-14Mbps 1080P60FPS, while using NDI output render path at 200Mbps encode to other receiving node simultaneously for those 8 hours, and the result is right here in the picture.  I will test with newer drivers and report back....
![image](https://user-images.githubusercontent.com/27184427/32393259-0583e600-c096-11e7-96a4-129703399caf.png)

**Comment by Benman2785** [comment] 2017-11-05 14:01
17.11.1 - HWacc still broken

**Comment by MikhailAMD** [comment] 2018-01-03 23:44
Back to this: if you still have a crash could you please generate and share dump file and dxdiag log? thnks,

**Comment by Benman2785** [comment] 2018-03-19 19:53
is fixed since 18.2.2 i think

**Comment by MikhailAMD** [comment] 2019-07-23 16:13
Closed as  fixed.

**Closed by MikhailAMD** 2019-07-23 16:13 UTC
