### ISSUE TITLE
Memory leak when i use vce to encode

### ISSUE THREAD

**Issue by jieytan** [GPUOpen-LibrariesAndSDKs/AMF#270] opened 2021-09-23 07:17 UTC
Hello

I want to apply amf encoder on video conferencing scenario,

This is my device info:
CPU - AMD Ryzen 7 4800H with Radeon Graphics
Radeon SW version - 20.50.02.11  Adrenalin
GPU - AMD Radeon(TM) Graphics

Here is the workflow:
//init
1.m_pFactory->CreateContext(&pContext);
**2.I set memory type to be HOST,  So i did not call context init;** 
3.m_pFactory->CreateComponent(pContext, AMFVideoEncoderVCE_SVC, &m_pAmfEncoder);
//surface alloc
4.pContext->CreateSurfaceFromHostNative(format, width, height, hStride, height, pIn, &pSurface, pObserver);
//enc
5.m_pAmfEncoder->SubmitInput(pSurface);
6.m_pAmfEncoder->QueryOutput(ppData);

During above workflow, i notice the **memory is increasing frame by frame**. 

To fix it, i've tried to use **pObserver.OnSurfaceDataRelease() to release pSurface**, that is to change the workflow like:
**5.pSurface->addObserver(pOb)  // release pSurface when callback**
6.m_pAmfEncoder->SubmitInput(pSurface);
7.m_pAmfEncoder->QueryOutput(ppData);

**However, this callback would return way too early that encoder fails.**

So here is my question:
**1. I use Host memory,  Is above workflow right? And will it worse performance compared to DX9 or DX11?** 
**2. How to manage the memory to avoid memory leak?**

Would you please help? Thank you very much.

**Comment by jieytan** [comment] 2021-09-24 03:47
Another question:

Code below from sample code CapabilityManager project is weird:
```        
amf_uint32 maxTemporalLayers = 0;
encoderCaps->GetProperty(AMF_VIDEO_ENCODER_CAP_MAX_TEMPORAL_LAYERS, &maxTemporalLayers);
std::wcout << L"\t\tNumber of temporal Layers:" << maxTemporalLayers << L"\n";
```
when i set maxTemporalLayers = 0, after getproperty, the maxTemporalLayers==0;
when i set maxTemporalLayers = 20, after getproperty, the maxTemporalLayers==20;

It seems like Getproperty is not working ?

**Comment by rhutsAMD** [comment] 2021-09-24 18:13
Regarding the possible leak, there are a few different possibilities that could be happening.
-	Are you using smart pointers? If not it could mean you have a leak in your code. Could you please share your sample app with source code that we can use to reproduce in-house?
-	Over how long of a period do you notice the memory growing, and if you let it continue does it eventually stabilize? This could be normal behaviour in the beginning. Also QueryOutput is just a query, it may not return output and the encoder should be queried properly by checking the result / output.


The callback will be called when the reference count to the surface is 0, at which point you can reuse/delete your own memory.

Submitting Host memory would still be converted to GPU memory before your surfaces are encoded anyways.

Regarding your second comment, you are mixing two property storages: AMFCaps and AMFComponent. AMFCaps is read-only and AMFComponent is read-write. AMFCaps is a maximum value, AMFComponentis the current value.

**Comment by jieytan** [comment] 2021-09-26 09:39
1.
Thank you for mention smart pointer!
I guess the conversion below may cause the reference number inside smart pointer go wrong?
```
amf::AMFDataPtr data;
m_pAmfBitstream = (amf::AMFBufferPtr)data.Detch();
```
Anyways now I now fix the memory leak. 

2.
Yes. and I am trying to use AMFCaps to get the maximum value.
However, i cannot get it. It keeps the initial value.

**Comment by jieytan** [comment] 2021-09-27 10:20
Another question:

```
    int roiSurf_w = (m_amfEncodeParam.w + 15) / 16;
    int roiSurf_h = (m_amfEncodeParam.h + 15) / 16;
    amf::AMFContext1Ptr spContext1(m_pAmfContext);
    for (int i = 0; i < iRoiNum; i++) {
        int roi_x = roiInfo->roi_rect.origin.x * dst_width / src_width /16;
        int roi_y = roiInfo->roi_rect.origin.y * dst_width / src_width /16;
        int roi_w = (roiInfo->roi_rect.size.width * dst_width / src_width + 15) / 16;
        int roi_h = (roiInfo->roi_rect.size.height * dst_width / src_width + 15) / 16;
        AMF_RESULT res = spContext1->AllocSurfaceEx(amf::AMF_MEMORY_HOST, amf::AMF_SURFACE_GRAY32, roiSurf_w, roiSurf_h,
            amf::AMF_SURFACE_USAGE_DEFAULT | amf::AMF_SURFACE_USAGE_LINEAR, amf::AMF_MEMORY_CPU_DEFAULT, &m_pAmfROISurface);
        if (res != AMF_OK)
        {
            printf("AMFContext::AllocSurface(amf::AMF_MEMORY_HOST) for ROI map failed!\n");
            
        }

        amf_uint32* buf = (amf_uint32*)m_pAmfROISurface->GetPlaneAt(0)->GetNative();
        amf_int32 pitch = m_pAmfROISurface->GetPlaneAt(0)->GetHPitch();
        memset((void*)buf, 0, pitch * roiSurf_h);

        for (int y = roi_y ; y < roi_y + roi_h ; y++)//?
        {
            for (int x = roi_x ; x < roi_x + roi_w ; x++)
            {
                buf[x + y * pitch / 4] = 5;
            }
        }
    }
```
Is this right way to set ROI? Why i cannot see any difference after set? And how does the number 5 take effects? Why need to /16?  
look forward to your reply!

**Comment by jieytan** [comment] 2021-10-14 04:27
Thank you. With your help, now i only got two final questions about D3D9.

I notice :

1. When i init context with D3D9 in sample code TranscodeHW. The converter does not support AMF_SURFACE_YUV420P as input. 

2. When i init context with D3D9 in sample code SampleROI, the ROI setting is not working. (In encoded output h264, the roi area's QP keeps the same as non-roi area)

Are these by design? Otherwise, how should i set to use converter and ROI with D3D9 correctly?

**Comment by jieytan** [comment] 2021-10-14 09:46
And with D3D11, the roi is working. 
However, if i create context with null device, which is like:
pContext->InitDX11(NULL);
Then, when i need to copy data from cpu to gpu texture, the call to ID3D11DeviceContext::Map() will fail and return E_INVALIDARG.
Then i will need to copy data to Host surface and then covert host surface to DX11 tecture, which might affect the performance. 
Any solution?

**Comment by jieytan** [comment] 2021-11-08 00:56
Thank you. Looking forward to the new build.

**Comment by rhutsAMD** [comment] 2021-11-18 21:52
The fix for the capability query with AMF_VIDEO_ENCODER_CAP_MAX_TEMPORAL_LAYERS is now publicly released in the Radeon™ Software Adrenalin 21.11.3 driver and I confirmed it is working with this driver. Similarly the fix for the AMF_VIDEO_ENCODER_ROI_DATA is included and has been verified. 

Additionally, the data provided through AMF_VIDEO_ENCODER_ROI_DATA to the encoder is actually an importance map of values ( [0, 10] inclusive ) which have an effect on the QP values of the corresponding Macroblocks. It is not a way of explicitly setting QP values. Furthermore, the individual importance map values are relative to the average importance, which is why the sample sets the outer region importance to 0 and sets the inner region importance to 10.

**Comment by jieytan** [comment] 2021-11-22 04:24
Indeed, It works now!
Thank you and your explanation.
BTW, do you also know when will the AMF_VIDEO_ENCODER_TARGET_BITRATE_TL fix be ready?

**Comment by jieytan** [comment] 2021-12-08 04:15
@MikhailAMD  Hi Sorry to bother you. Any updates?

**Comment by rhutsAMD** [comment] 2021-12-08 16:56
Could you please try with the latest public release driver? We were not able to reproduce the issue with Radeon™ Software Adrenalin 21.12.1.

**Comment by jieytan** [comment] 2021-12-09 01:49
That is strange. I still have this issue with Adrenalin 21.12.1.

**Comment by jieytan** [comment] 2021-12-09 01:56
> Hi. I've reproduced the problem. With driver update a new encoder code is used so the difference in behavior. To get around the issue you can move setting of bitrate by layers after Init() call. It should work with older driver as well. In any case, bitrate is dynamic parameter and can be set at any time. I will open internal ticket.

@MikhailAMD Sorry to bother you. Can you still reproduce this issue on your side? Or you've managed to fix it?

**Comment by rhutsAMD** [comment] 2021-12-14 17:41
There are two issues, the first is regarding setting the temporal enhancement layer bitrate before vs. after encoder->Init(). This has been fixed and is available in the latest public driver.

The second issue is a mix up of the layers. Please swap the bitrates you are currently setting to have the larger bitrate set for “TL1”.
Layer #1 “TL1.QL0.<param>” is the full stream and cannot be requested to have a smaller bitrate than the reduced stream.
Layer #0 “TL0.QL0.<param>” is the reduced stream and should have the smaller bitrate requested.

We will update the documentation to clarify this differentiation between the layers. Also, the SVCSplitter sample will be updated to add more tracing and generation of all of the layers.

**Comment by jieytan** [comment] 2021-12-15 03:48
On the first issue, how can i get the latest public driver? I try to update from device manager and AMD Radeon Software, but it won't work.

On the second issue. Thanks for clarifying.
So if I what to encode 2 layers. total biterate is 3M, and the ratio is 2:1, How can i set it?

Thank you very much for helping.

**Comment by jieytan** [comment] 2021-12-21 02:05
@rhutsAMD Hi When will the doc be updated?

**Comment by rhutsAMD** [comment] 2022-01-13 18:31
For the 3 layer case, continue setting the per layer parameters following the same pattern i.e. with “TL2.QL0.” having the highest bitrate, and down to the base temporal layer “TL0.QL0.” having the lowest bitrate. This can be expanded to as many temporal layers as your setup supports.

The documentation will be updated in the next AMF release. In the meantime, I will share the updated information below:

__2.2.4  SVC Properties__
SVC encoding is enabled by setting the number of temporal enhancement layers to a value that is greater than 1 before initializing the encoder. The maximum number of temporal layers supported by the encoder can be queried from the encoder capabilities before initializing the encoder.

To define SVC parameters per layer, the following format must be used:
&nbsp;&nbsp;&nbsp;&nbsp; TL<Temporal_Layer_Number>.QL<Quality_Layer_Number>.<Parameter_name>

As an example with two temporal layers, to configure “Target bitrate” for the base/first temporal layer and first quality layer, the following parameter should be used:
&nbsp;&nbsp;&nbsp;&nbsp; “TL0.QL0.TargetBitrate”

To configure “Target bitrate” for the second temporal layer and first quality layer, the following parameter should be used:
&nbsp;&nbsp;&nbsp;&nbsp; “TL1.QL0.TargetBitrate”

When setting per layer parameters, the equivalent non-SVC layer parameters should not be set for the encoder otherwise the per layer configuration will be overwritten.

Remark: quality layers are not supported on VCE 1.0. “QL0” must be used for quality layers.

**Closed** 2022-01-18 09:09 UTC
