### ISSUE TITLE
[Bug]: Capability Manager's information about HEVC encoding does not match.

### ISSUE THREAD

**Issue by Masa-tam** [GPUOpen-LibrariesAndSDKs/AMF#307] opened 2022-04-07 05:37 UTC
- OS: Windows 10 21H2
 - Driver Version 22.3.1/22.4.1
 - GPU RX 5500 XT / RX 6600
 - Which component has the issue Encoder capability

Attached is the text obtained from Capability Manager.
On the RX5500XT, the values are different depending on the PC on which it was run.
[RX5500XT_machine_a.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8439899/RX5500XT_machine_a.txt)
[RX5500XT_machine_b.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8439900/RX5500XT_machine_b.txt)

On the RX6600, HEVC Main10 support may appear and disappear each time it is run, even on the same PC.
[RX6600_result_a.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8439915/RX6600_result_a.txt)
[RX6600_result_b.txt](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/files/8439916/RX6600_result_b.txt)

**Comment by Masa-tam** [comment] 2022-04-08 00:30
The currently installed display driver version is 22.3.1.
The amfrt64.dll in System32 / DriverStore is 1.4.24.0.
The SHA256 hash was identical at 9af20db96216b320a5c5ecde7cba5e73d3d76721790e5b1676d539ad6e8ce78.

**Comment by MikhailAMD** [comment] 2022-04-08 14:31
You can run CapabilityManager in debugger, breakpoint and check where DLLs are loaded from in VS Modules View.

**Comment by Masa-tam** [comment] 2022-04-11 00:53
I checked the module list in the debugger and 1.4.24 is loaded as shown in the attached screenshot.
![debugger](https://user-images.githubusercontent.com/31396809/162647730-5b5617d8-261f-4f77-a701-5d8d3116327f.png)

The following code displays the version of CapabilityManager.
```
    wprintf(L "AMF version (header): %I64X\n", AMF_FULL_VERSION);
    wprintf(L "AMF version (runtime): %I64X\n", g_AMFFactory.AMFQueryVersion());
```
I think 1000400180000 is 1.4.24.0.

**Comment by MikhailAMD** [comment] 2022-04-12 13:28
OK, thanks, logs show some valuable data. While I couldn't reproduce this, I am opening internal ticket.

**Comment by Masa-tam** [comment] 2023-06-09 08:13
- OS: Windows 11 22H2
- Driver: Version 23.5.1
- GPU: RX 7600

I have a new PC and the OS / GPU / drivers have changed, but the situation has not changed.
HEVC Capability returns a response that only the Main profile is supported.

**Comment by MikhailAMD** [comment] 2023-06-09 14:48
Hmmm... The internal ticket marked as resolved a while ago and currently I don't see conditional logic in AMF about P010 support in HEVC. 
Is it possible that Windows update installed an old driver? I saw this a lot. 
Could you please check version in Device Manager? 
Can you check AMF version returned from AMFQueryVersion? CapabilityManager traces it.
Another indicator of the old driver is loaded atidxx64.dll. This is D3D11 driver and was replaced with amdxx64.dll

Another strange issue: I see "Invalid DXGI_FORMAT 67 specified" in the logs. AMF doesn't use this format at all. ID3D11DeviceContext::CreateVideoDecoder is called with other formats. I wonder why do we see this? Is it possible, some kind of DLL shim is used?

**Comment by Masa-tam** [comment] 2023-06-13 01:22
Capability manager responded as follows: 
```
AMF version (header):  10004001D0000
AMF version (runtime): 10004001E0000
```
Capability manager has loaded c:\windows\system32\amfrt64.dll.
The properties of this amfrt64.dll are as follows:
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/31396809/88f923cd-d546-49d5-b044-a9ceb25bcfbc)

I have installed whql-amd-software-adrenalin-edition-23.5.1-win10-win11-for-radeon-rx-7600.exe.
The Windows folder C:\Windows\System32 had atidxx64.dll, but amdxx64.dll did not exist.

The driver versions in Device Manager were as follows.
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/31396809/eb41422c-7855-4364-8153-1ba453d171f9)

The driver file details also showed atidxx64.dll but not amdxx64.dll.
![image](https://github.com/GPUOpen-LibrariesAndSDKs/AMF/assets/31396809/ddda9bba-4be0-4282-9579-b22de82fea36)

**Comment by MikhailAMD** [comment] 2023-06-13 13:35
Thanks, we are trying to repro but could you please provide debug output for CapabilityManager with this latest driver? In the earlier logs I see old driver DLLs only, I want to be sure that now the right driver is used.

**Closed** 2024-04-04 19:49 UTC
Labels: bug
